### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by nonameolsson** [panz3r/hyper-spotify#15]
Looks like a great plugin! But I have no idea how to use it, and can't find any more instructions than those that I already have tried.

I have installed it, and DevTools don't throw any errors. It is obvious that it shows up, because I can switch position and margin. But it is just empty.
https://puu.sh/y61yf/8282eb999a.png

Do I need to install or configure anything else?

**Comment by panz3r** [comment]
Hi @nonameolsson ,

Thanks for your feedback, this plugin interacts directly with the `Spotify App` for MacOS and Linux (downloadable from [here](https://www.spotify.com/download/other/), so you have to install it before being able to use this plugin. Also note that Windows is not supported by this plugin.

From your screenshot I cannot clearly see the `hyper-spotify` bar but I noticed that you have `hyper-statusline` installed and so I suggest you to set the `margin` option of `hyper-spotify` to `double` if you have `position` set as `bottom` since I originally intended that to let my plugin work well when paired with `hyper-statusline`.

Let me know if I can help you any further.

**Comment by LetoGear** [comment]
I've encountered the same situation.
Instead of altering configurations, I changed **orders** of `hyper-spotify` and `hyper-statusline` in plugins:

**From**
```javascript
plugins: [
    "hyper-statusline",
    ...
    "hyper-spotify",
]
```
**To**
```javascript
plugins: [
    "hyper-spotify",
    "hyper-statusline",
    ...
]
```

and it worked :)

**Comment by watain666** [comment]
Same issue here
I even try the @LetoGear suggest, but still not working

* os : Ubuntu 18.04
* Hyper : Hyper 2.0.0 (stable)

Gnome default media info & my conky script working just fine

![](https://i.dbree.stream/WcdP6fYYOpJPaw/original_hyper-spotify_issue_1.png)

When I click `About Hyper`

I didn't see hyper-spotify in plugins list, is that reason?

![](https://i.dbree.stream/DsNpuwkOqNY1Gw/original_hyper-spotify_issue_2.png)

**Comment by panz3r** [comment]
Hi @watain666 , 

> I didn't see hyper-spotify in plugins list, is that reason?

That's most probably the issue here, Hyper is not installing `hyper-spotify` plugin.

Can you try to force-install the plugin by running this command?
```sh
cd ~/.hyper_plugins && npm install
```

**Comment by panz3r** [comment]
@watain666, you can find a solution to the problem here 
https://github.com/panz3r/hyper-spotify/issues/24#issuecomment-436237172

It seems version `5.0.0` is broken.

**Comment by panz3r** [comment]
This issue is more than a year old, closing due to ageing.

If still relevant after version `5.0.0`, please open a new issue.
