### ISSUE TITLE
win32 does not work

### ISSUE THREAD

**Issue by Milo123459** [panz3r/hyper-spotify#35]
PS C:\Users\milo5\AppData\Roaming\hyper> cd .hyper_plugins
PS C:\Users\milo5\AppData\Roaming\hyper\.hyper_plugins> npm i
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for hyper-spotify@5.3.1: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    !win32
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\milo5\AppData\Roaming\npm-cache\_logs\2020-07-06T13_45_36_336Z-debug.log
PS C:\Users\milo5\AppData\Roaming\hyper\.hyper_plugins> ^C
theres the error, tried hard to fix but cant get working :(

**Comment by panz3r** [comment]
Hi @Milo123459 ,

Thanks for the interest in this project, unfortunately `Windows` is no longer supported by this plugin because of changes made to the Spotify client app.

See issue #23  for more details about this and to follow the developments, I don't have an exact timeframe since I don't have much time to work on this currently.

**Comment by Milo123459** [comment]
ok thanks
